import Toaster from '@/components/ui/Toast'

import Providers from './providers'
import './globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = async ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => (
	<html lang="en" suppressHydrationWarning>
		<body className="h-screen">
			<Providers>{children}</Providers>
			<Toaster position="top-center" richColors />
		</body>
	</html>
)

export default RootLayout
