import Toaster from '@/components/ui/Toast'
import { LOCALES, type LOCALES_TYPES } from '@/constants'

import Providers from './providers'
import './globals.css'

import type { Metadata } from 'next'

type Props = React.PropsWithChildren<{ params: { locale: LOCALES_TYPES } }>

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export function generateStaticParams() {
	return LOCALES.map(locale => ({ locale }))
}

const RootLayout = async ({ children, params: { locale } }: Readonly<Props>) => (
	<html lang={locale} suppressHydrationWarning>
		<body className="h-screen">
			<Providers>{children}</Providers>
			<Toaster position="top-center" richColors />
		</body>
	</html>
)

export default RootLayout
